### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [santhosh-r/TaggableFS#1]
Hi, which license applies to this project?

I would like to learn from your project how to implement such a filesystem, but can not without a suitable license specified...

Kind regards
Neo

**Comment by santhosh-r** [comment]
Hey Neo, sorry about the very late reply. I just added the MIT license. Its mainly based on Prof Pfeiffer's tutorial from here https://www.cs.nmsu.edu/~pfeiffer/fuse-tutorial/ and the rest is code to use sqlite to store and retrieve files using tags.

**Comment by LifeCANvs** [comment]
> Hey Neo, sorry about the very late reply. I just added the MIT license. Its mainly based on Prof Pfeiffer's tutorial from here https://www.cs.nmsu.edu/~pfeiffer/fuse-tutorial/ and the rest is code to use sqlite to store and retrieve files using tags.

Thank you!
